import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/**
 * Ground truths for the e2e suite, read from the parser's generated JSON rather
 * than hard-coded.
 *
 * Pinning literals ("232 Papers", "6 papers") couples every content merge to the
 * test suite: adding papers silently reddens tests that have nothing to do with
 * the change, and the failures get triaged as noise. Deriving them instead turns
 * each assertion into a real parser-to-render consistency check — the page must
 * show what the parser emitted — which is the thing worth testing.
 *
 * These files are build artifacts (gitignored, regenerated by `pnpm parse`), and
 * `pnpm build` runs the parser, so they exist whenever the e2e suite runs.
 */
const dataDir = fileURLToPath(new URL('../src/content/data/', import.meta.url));
const read = <T>(name: string): T => JSON.parse(readFileSync(`${dataDir}${name}`, 'utf8')) as T;

type Counts = { papers: number; software: number; databases: number; species: number; datasets: number };
type Cell = { method: string; area: string; refIds: number[] };
type Ref = { id: number; section: string };
type Papers = { cells: Cell[]; references: Ref[] };
type Metrics = { species: { species: string; inventoryRows: number; isStub: boolean }[] };
type PrimerItem = { kind: string; internal: boolean };
type Primers = { primers: { slug: string; sections: { items: PrimerItem[] }[] }[] };

export const counts = read<Counts>('counts.json');
export const papers = read<Papers>('papers.json');
export const metrics = read<Metrics>('metrics.json');
export const primers = read<Primers>('primers.json');

/** How many references sit in a given matrix cell. */
export function cellRefCount(method: string, area: string): number {
  const cell = papers.cells.find((c) => c.method === method && c.area === area);
  if (!cell) throw new Error(`no matrix cell for ${method} × ${area}`);
  return cell.refIds.length;
}

/**
 * References cited by no matrix cell — the corpus the /papers/reviews/ page
 * surfaces (reviews, perspectives, and the reference-work shelves). Derived the
 * same way the ReferenceShelf island derives it, so the test tracks the render.
 */
export function matrixUnreachedRefs(): Ref[] {
  const cited = new Set<number>();
  for (const c of papers.cells) for (const id of c.refIds) cited.add(id);
  return papers.references.filter((r) => !cited.has(r.id));
}

/** Section → unreached-ref count, i.e. the reviews page's group headings. */
export function unreachedSectionCounts(): Map<string, number> {
  const m = new Map<string, number>();
  for (const r of matrixUnreachedRefs()) m.set(r.section, (m.get(r.section) ?? 0) + 1);
  return m;
}

/** Species pages with zero catalogued deposits — the "where help is wanted" signal. */
export const stubSpeciesCount = metrics.species.filter((s) => s.isStub).length;

/**
 * Items a primer renders as an external, new-tab card (`a.talk-card[target=_blank]`).
 * Mirrors PrimerHub.astro: videos embed, internal links get `.primer-nav`.
 */
export function externalCardCount(slug: string): number {
  const primer = primers.primers.find((p) => p.slug === slug);
  if (!primer) throw new Error(`no primer with slug ${slug}`);
  return primer.sections
    .flatMap((s) => s.items)
    .filter((i) => i.kind !== 'video' && !i.internal).length;
}
