#!/usr/bin/env python3
"""Guard the pure parts of the accession chain: patterns, cues, title joins.

Every case here is a string that appeared in a real paper in the corpus, or the
shape of one. None of it needs Docling, Zotero, the network or the gitignored
`docling-corpus/`, which is why CI can run it.

Run:  python3 .claude/skills/matrix-classification-audit/extract_accessions.test.py

The first block is the one that matters: an accession pattern loose enough to
admit a gene symbol reports a paper's biology as its deposits, and that is what
`SAM[END][AG]?\\d+` did to ref 120's interferon-stimulated-gene table.
"""
import json
import os
import re
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(os.path.dirname(HERE), "zotero-collection-scope"))

import extract_accessions as ea  # noqa: E402
import fetch_accession_citations as fc  # noqa: E402

fails = 0


def check(name, got, want):
    global fails
    ok = got == want
    if not ok:
        fails += 1
    print(f'  [{"PASS" if ok else "FAIL"}] {name}')
    if not ok:
        print(f"         got {got!r}, want {want!r}")


# ---------------------------------------------------------------------------
print("\n=== accession patterns: what is and is not an accession ===")

# (text, expected {token: registry})
PATTERN_CASES = [
    # The defect. SAMD9 and SAMD9L are genes; they sat in a table of
    # interferon-stimulated genes in ref 120 and one of them was reported as a
    # BioSample. Real BioSample ids never carry a single digit.
    ("PLSCR1, RSAD2, SAMD9, SAMD9L, SELL, STAT2, TAP1", {}),
    ("Raw reads are under SAMN12345678 and SAMEA104416737.",
     {"SAMN12345678": "BioSample", "SAMEA104416737": "BioSample"}),
    ("DDBJ BioSample SAMD00012345.", {"SAMD00012345": "BioSample"}),

    # The registries the corpus actually uses.
    ("deposited in GEO under GSE146974", {"GSE146974": "GEO"}),
    ("BioProject PRJNA1119173 and PRJEB58031",
     {"PRJNA1119173": "BioProject", "PRJEB58031": "BioProject"}),
    ("runs SRR11351697, SRP073767", {"SRR11351697": "SRA", "SRP073767": "SRA"}),
    ("ArrayExpress E-MTAB-5061", {"E-MTAB-5061": "ArrayExpress"}),
    ("archived at https://doi.org/10.5281/zenodo.6811225",
     {"10.5281/zenodo.6811225": "Zenodo DOI"}),
    ("10.6084/m9.figshare.28980254", {"10.6084/m9.figshare.28980254": "Figshare DOI"}),
    ("dbGaP phs000424.v10.p2", {"phs000424.v10.p2": "dbGaP"}),

    # A bare number is never an accession, whatever it looks like.
    ("cells were seeded at 146974 per well and 12345678 total", {}),
    # A gene list is the common false-positive source; none of these matches.
    ("MX1, OAS1, USP18, TRIM5, WARS1, LY6E, MOV10", {}),
]

for text, want in PATTERN_CASES:
    got = {tok: reg for tok, (reg, _kind) in ea.find_accessions(text).items()}
    check(repr(text[:56]), got, want)


# ---------------------------------------------------------------------------
print("\n=== sentence cues: deposit, reuse, or neither ===")

# Asserted through find_accessions rather than classify(), because the window
# the classifier sees is half the behaviour: which text reaches it decides the
# answer as much as the cues do.
CUE_CASES = [
    # Ref 5's own deposit, verbatim. It names both who made the data and where
    # a reader gets it; only the first is evidence about provenance.
    ("The human monocyte data generated by us can be downloaded from GEO "
     "(GSE146974).", {"GSE146974": "deposit"}),
    ("single-cell datasets were obtained from GSE81076 and E-MTAB-5061",
     {"GSE81076": "reuse", "E-MTAB-5061": "reuse"}),
    ("Raw sequencing data have been deposited in the SRA under PRJNA1119173.",
     {"PRJNA1119173": "deposit"}),
    ("We analysed publicly available data from GSE85241.", {"GSE85241": "reuse"}),
    # One sentence, two clauses, opposite answers. Read whole, each accession
    # inherits the other's evidence and both collapse to unclear.
    ("Data generated in this study were deposited in GEO under GSE111111; "
     "other datasets were downloaded from ArrayExpress (E-MTAB-5061)",
     {"GSE111111": "deposit", "E-MTAB-5061": "reuse"}),
    # Ownership is first-person only. Someone else generating the data is the
    # textbook reuse case and must not trip the ownership rule.
    ("The macaque retina data generated by Peng et al. are in GSE118480",
     {"GSE118480": "unclear"}),
    # No cue at all -- a bare table row or a bare parenthetical.
    ("Mouse hematopoietic stem cells (GSE72857)", {"GSE72857": "unclear"}),
]
for text, want in CUE_CASES:
    got = {tok: kind for tok, (_reg, kind) in ea.find_accessions(text).items()}
    check(repr(text[:56]), got, want)


# ---------------------------------------------------------------------------
print("\n=== title joins: used only where one side has no PubMed id ===")

TITLE_CASES = [
    # Ref 10 against its Zenodo record: exact.
    ("Controlling gene expression with deep generative design of regulatory DNA",
     "Controlling gene expression with deep generative design of regulatory DNA",
     True),
    # Ref 91 against its figshare record, which wraps the title in boilerplate
    # AND hyphenates differently. Splitting on the hyphen loses this join;
    # deleting it keeps it.
    ("Pretraining a foundation model for small-molecule natural products",
     "Data Archiving and Access for NaFM: Pre-training a Foundation Model for "
     "Small-Molecule Natural Products",
     True),
    # A different paper in the same field shares vocabulary but not the title.
    ("scBERT as a large-scale pretrained deep language model for cell type "
     "annotation of single-cell RNA-seq data",
     "Single-Cell Transcriptome Profiling of Human Pancreatic Islets in Health "
     "and Type 2 Diabetes",
     False),
    # Generic record titles must never match: too few content words to mean
    # anything, so the minimum-token floor rejects them outright.
    ("Controlling gene expression with deep generative design of regulatory DNA",
     "Supplementary Data", False),
    ("A multi-tissue single-cell expression atlas in cattle", "Dataset", False),
]
for paper, record, want in TITLE_CASES:
    check(f"{paper[:34]!r} ~ {record[:34]!r}", fc.titles_match(paper, record), want)

check("stopwords alone cannot carry a match",
      fc.titles_match("the data of the data", "the data and the data"), False)


# ---------------------------------------------------------------------------
print("\n=== the verdict cache is keyed by (ref, accession) ===")

# The five accessions below are each declared by two papers in this corpus.
# GSE118480 is ref 115's deposit and ref 5's reuse, so a cache keyed by the
# accession alone answers for one paper and repeats that answer for the other.
with tempfile.TemporaryDirectory() as tmp:
    p = os.path.join(tmp, "cites.json")

    with open(p, "w") as fh:
        json.dump({"schema": 2, "verdicts": {
            "115:GSE118480": {"verdict": "deposit", "evidence": "pmid-match"},
            "5:GSE118480": {"verdict": "reuse", "evidence": "pmid-other"}}}, fh)
    loaded = ea.load_citations(__import__("pathlib").Path(p))
    check("both papers' verdicts survive", sorted(loaded), ["115:GSE118480", "5:GSE118480"])
    check("and they differ", loaded["5:GSE118480"]["verdict"], "reuse")

    # A schema-1 file was keyed by accession alone and cannot be migrated: its
    # verdicts do not record which paper they were gathered about. Reading it as
    # an empty result would silently demote every accession to the sentence
    # guess, which looks identical to having no cache at all.
    with open(p, "w") as fh:
        json.dump({"GSE118480": {"verdict": "deposit"}}, fh)
    check("an unrecognised schema is refused, not read",
          ea.load_citations(__import__("pathlib").Path(p)), {})

    check("an absent cache is simply empty",
          ea.load_citations(__import__("pathlib").Path(os.path.join(tmp, "nope.json"))), {})


# ---------------------------------------------------------------------------
print("\n=== every script in this directory is listed in the README ===")

# This repo's most expensive recurring defect is a hand-maintained fact beside
# the thing that already knows it. The README's script table is exactly that,
# and it had already drifted: it listed neither accession script for two
# commits. Deriving the table is not worth it; failing when it drifts is.
readme = open(os.path.join(HERE, "README.md"), encoding="utf-8").read()
scripts = sorted(f for f in os.listdir(HERE)
                 if f.endswith((".py", ".mjs")) and not f.startswith("_"))
missing = [f for f in scripts if f not in readme]
check("README documents every script", missing, [])


print(f'\n{"FAILED" if fails else "OK"}: {fails} failure(s)')
sys.exit(1 if fails else 0)
