#!/usr/bin/env python3
"""Extract deposit accessions from each paper's availability statement (CAAIL-259).

`papers-dataset-audit` finds accessions by grepping the flat full-text cache for
accession-shaped patterns. That cannot tell a deposit from a citation: `GSE173199`
matches identically whether the paper deposited it or analysed someone else's copy
of it, and those have opposite consequences for the inventory.

The ingest makes the distinction structural. An accession inside a bounded
data-availability statement is one the paper is announcing. One that appears only
in the introduction or the reference list is one it is citing. This reports both,
labelled, and never merges them.

    python3 .claude/skills/matrix-classification-audit/extract_accessions.py
    python3 .claude/skills/matrix-classification-audit/extract_accessions.py --orphans
    python3 .claude/skills/matrix-classification-audit/extract_accessions.py --json out.json

`--orphans` additionally greps the repo for each declared accession and reports
the ones CAAIL does not hold anywhere. That is the input to a curation decision,
not the decision: this cannot say whether an accession belongs in the inventory,
only that the paper names it and the repo does not mention it.

Two things decide whether an accession is a deposit or reused data, and the tool
says which one decided each. `fetch_accession_citations.py` asks the registry
which paper its record belongs to, which is a fact about the record. Where the
registry is silent or does not cover it, a heuristic reads the clause around the
accession, which is a guess. Registry evidence always wins.

Most of the corpus turns out to be reused data, which is why the distinction is
load-bearing rather than pedantic: an early version of this reported every absent
accession as a gap in CAAIL's inventory, and most of that number was papers'
bibliographies.

Snapshot 2026-08-12, printed by the two commands above -- run them rather than
trusting this: **144 accessions across 63 refs; 93 reuse, 16 deposit, 34 unclear,
1 not an accession.** Only **2** of the 144 now rest on the sentence guess; the
registry settles 92 and is honestly silent on 49. Six deposits are absent from
CAAIL's curated content, three of them found only once Zenodo and figshare were
resolvable.

Stdlib only. Reads the gitignored docling-corpus/ written by docling_ingest.py.
"""
import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]

# Registry patterns. Each is anchored on a word boundary and requires the
# registry's own prefix, so a bare number never matches.
REGISTRIES = [
    ("GEO",            re.compile(r"\bGSE\d{3,}\b")),
    ("GEO sample",     re.compile(r"\bGSM\d{3,}\b")),
    ("BioProject",     re.compile(r"\bPRJ(?:NA|EB|DB)\d{3,}\b")),
    ("SRA",            re.compile(r"\bSR[PRXS]\d{4,}\b")),
    ("ENA",            re.compile(r"\bERP\d{4,}\b")),
    ("ArrayExpress",   re.compile(r"\bE-[A-Z]{4}-\d+\b")),
    ("PRIDE",          re.compile(r"\bPXD\d{4,}\b")),
    ("MassIVE",        re.compile(r"\bMSV\d{6,}\b")),
    ("Metabolights",   re.compile(r"\bMTBLS\d+\b")),
    ("dbGaP",          re.compile(r"\bphs\d{6}(?:\.v\d+\.p\d+)?\b")),
    # SAMN / SAMD / SAMEA / SAMEG, and never fewer than five digits: the
    # unbounded `\d+` form matched `SAMD9`, an interferon-stimulated GENE, out of
    # a table of them in ref 120. An accession pattern loose enough to admit a
    # gene symbol reports the paper's biology as its deposits.
    ("BioSample",      re.compile(r"\bSAM(?:N|D|E[AG])\d{5,}\b")),
    ("EGA",            re.compile(r"\bEGA[SD]\d{5,}\b")),
    ("PDB",            re.compile(r"\bPDB[:\s]+[0-9][A-Za-z0-9]{3}\b")),
    ("Zenodo DOI",     re.compile(r"\b10\.5281/zenodo\.\d+\b", re.IGNORECASE)),
    ("Figshare DOI",   re.compile(r"\b10\.6084/m9\.figshare\.\d+\b", re.IGNORECASE)),
    ("Dryad DOI",      re.compile(r"\b10\.5061/dryad\.[a-z0-9]+\b", re.IGNORECASE)),
]

GITHUB_RE = re.compile(r"\bgithub\.com/([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)")

# Being inside a data-availability statement is NOT enough to call an accession a
# deposit. Availability statements routinely announce reused data: "single-cell
# datasets were obtained from GSE81076, GSE85241 and E-MTAB-5061". Ref 54 lists
# 23 GEO accessions in a table of data sources, none of them its own. Treating
# those as deposits would report a paper's bibliography as missing inventory.
#
# So classify by the language around the accession. This is a heuristic and is
# reported as one: the categories are deposit, reuse and unclear, and unclear is
# not folded into either.
# First-person ownership of the data, which OUTRANKS a reuse cue rather than
# tying with it. "The human monocyte data generated by us can be downloaded from
# GEO (GSE146974)" says both who made the data and where a reader gets it, and
# only the first is evidence about provenance -- access language appears in
# deposits and reuse alike. That sentence is ref 5's own deposit, and the flat
# tie rule called it unclear.
#
# Deliberately narrow: it requires "us"/"we"/"this study", so "data generated by
# Peng et al." is not ownership. A cue that fires on "data generated" alone
# would claim every reused dataset the paper describes.
OWNERSHIP_CUES = re.compile(
    r"generated\s+(?:by\s+us\b|in\s+this\s+\w+|for\s+this\s+\w+)|"
    r"we\s+(?:generated|deposited|produced|submitted)|"
    r"(?:reported|produced|described)\s+in\s+this\s+\w+|"
    r"newly\s+generated|our\s+(?:own\s+)?(?:data|dataset)", re.IGNORECASE)

DEPOSIT_CUES = re.compile(
    r"deposit|submitted\s+to|generated\s+(?:in|for|during)\s+this|"
    r"reported\s+in\s+this|produced\s+in\s+this|"
    r"data\s+generated|newly\s+generated|"
    r"have\s+been\s+made\s+available|we\s+have\s+deposited|"
    r"accession\s+(?:code|number)s?\s+(?:is|are)", re.IGNORECASE)

REUSE_CUES = re.compile(
    r"obtained\s+from|downloaded\s+from|retrieved\s+from|"
    r"were\s+(?:taken|sourced)\s+from|publicly\s+available|previously\s+published|"
    r"from\s+the\s+(?:GEO|SRA|ENA|ArrayExpress)|"
    r"we\s+(?:used|analy[sz]ed|collected)|"
    r"third[\s-]party|external\s+dataset", re.IGNORECASE)


def _context(text, start, end, width=260):
    """The clause around a match, for cue classification.

    Sentence first, then narrowed to the clause the accession sits in. One
    sentence routinely announces a deposit and names reused data in two clauses
    -- "data generated in this study were deposited in GEO; other datasets were
    downloaded from ArrayExpress" -- and handing the whole sentence to both
    accessions gives each the other's evidence, which reads as a contradiction
    and resolves to unclear for both.
    """
    lo = text.rfind(".", 0, max(0, start - 1))
    lo = 0 if lo < 0 or start - lo > width else lo + 1
    hi = text.find(".", end)
    hi = len(text) if hi < 0 or hi - end > width else hi
    clause_lo = text.rfind(";", lo, start)
    clause_lo = lo if clause_lo < 0 else clause_lo + 1
    clause_hi = text.find(";", end, hi)
    clause_hi = hi if clause_hi < 0 else clause_hi
    return text[clause_lo:clause_hi]


def classify(context):
    """deposit | reuse | unclear, from the language around an accession."""
    if OWNERSHIP_CUES.search(context):
        return "deposit"
    dep, reuse = DEPOSIT_CUES.search(context), REUSE_CUES.search(context)
    if dep and not reuse:
        return "deposit"
    if reuse and not dep:
        return "reuse"
    return "unclear"


def find_accessions(text):
    """{accession: (registry, kind)} for every accession-shaped token in `text`."""
    found = {}
    for registry, pat in REGISTRIES:
        for m in pat.finditer(text or ""):
            tok = m.group(0).strip()
            if tok not in found:
                found[tok] = (registry, classify(_context(text, m.start(), m.end())))
    return found


CITATIONS_SCHEMA = 2


def load_citations(path):
    """The registry verdicts written by fetch_accession_citations.py, or {}.

    Refuses a schema it does not recognise rather than reading it as an empty
    result. The two look identical downstream -- every accession falls back to
    the sentence guess -- and a silent fallback to the weaker evidence is the
    failure mode worth being loud about.
    """
    if not path.is_file():
        return {}
    try:
        blob = json.loads(path.read_text())
    except ValueError:
        return {}
    if isinstance(blob, dict) and blob.get("schema") == CITATIONS_SCHEMA:
        return blob.get("verdicts", {})
    print(f"WARNING: {path} is not schema {CITATIONS_SCHEMA}; ignoring it. "
          "Re-run fetch_accession_citations.py.\n")
    return {}


# Where CAAIL actually holds things: the canonical curated content, plus the
# NDJSON the structured half of it is generated from. Deliberately NOT the whole
# repo. This script's own README and comments quote real accessions as examples,
# and an unscoped `git grep` reported one of those comments as evidence that
# CAAIL inventories GSE146974 -- suppressing the very orphan the example was
# about. Prose discussing an accession is not an inventory of it.
CONTENT_PATHS = [
    "Papers.md", "Software.md", "Databases.md", "Datasets", "OtherResources.md",
    "ReferenceWorks.md", "AwesomeLists.md", "Funding.md", "ResearchAreas",
    "Talks.md", "Primers", "Taxonomy.md", "site/db/ndjson",
]


def repo_mentions(token):
    """Does CAAIL's curated content mention this token? Uses git grep, so it is
    fast and respects .gitignore -- the point is what CAAIL PUBLISHES, not what
    happens to sit in a local artifact directory."""
    r = subprocess.run(["git", "grep", "-qiF", "-e", token, "--", *CONTENT_PATHS],
                       cwd=REPO, capture_output=True, text=True)
    return r.returncode == 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--corpus", default=str(REPO / "docling-corpus"))
    ap.add_argument("--orphans", action="store_true",
                    help="also check each declared accession against the repo")
    ap.add_argument("--json", default="")
    ap.add_argument("--citations",
                    default=str(REPO / "docling-corpus/accession-citations.json"),
                    help="fetch_accession_citations.py output. When present its "
                         "verdicts override the sentence heuristic, because the "
                         "registry knows and the sentence only hints.")
    args = ap.parse_args()

    # Registry evidence, if it has been fetched. An accession whose registry
    # record names this paper is a deposit; one whose record names a different
    # paper is data the authors reused. That is a fact about the record rather
    # than a reading of a sentence, so it wins wherever it exists.
    #
    # Keyed "<ref>:<accession>", because the question is about the PAIR. Five
    # accessions here are declared by two papers each -- GSE118480 is ref 115's
    # deposit and ref 5's reuse -- so a per-accession key answers for one paper
    # and quietly repeats that answer for the other.
    cites = load_citations(Path(args.citations))

    sec_dir = Path(args.corpus) / "sections"
    paths = sorted(sec_dir.glob("ref-*.json"), key=lambda x: int(x.stem.split("-")[1]))
    if not paths:
        sys.exit(f"no sections in {sec_dir}; run docling_ingest.py first")

    rows = []
    for p in paths:
        d = json.loads(p.read_text())
        declared = {}
        for a in d.get("availability", []):
            for tok, (reg, kind) in find_accessions(a["text"]).items():
                declared.setdefault(tok, {"registry": reg, "kind": kind,
                                          "where": a["heading"],
                                          "page": a["page_start"]})
        # Tables carry deposits too (a KEY RESOURCES TABLE lists them as rows),
        # but a table of data SOURCES looks identical, and a table row carries no
        # sentence to classify. So table hits are never called deposits.
        for t in d.get("tables", []):
            for tok, (reg, _kind) in find_accessions(t.get("markdown", "")).items():
                declared.setdefault(tok, {"registry": reg, "kind": "unclear",
                                          "where": "table", "page": t.get("page")})
        repos = sorted({m.group(1).rstrip(".,);")
                        for a in d.get("availability", [])
                        for m in GITHUB_RE.finditer(a["text"])})
        for tok, meta in declared.items():
            v = cites.get(f'{d["id"]}:{tok}', {})
            meta["source_of_kind"] = "sentence"
            meta["content"] = v.get("content", "data")
            if v.get("verdict") in ("deposit", "reuse"):
                meta["kind"] = v["verdict"]
                # A title join is still the record's own metadata, but it is a
                # weaker join than an id and a curator should be able to see
                # which one they are reading.
                meta["source_of_kind"] = (
                    "registry (title join)"
                    if v.get("evidence", "").startswith("title")
                    else "registry")
                meta["evidence"] = v.get("evidence", "")
            elif v.get("verdict") == "no-linked-citation":
                meta["source_of_kind"] = "registry-silent"
            elif v.get("verdict") == "not-found":
                # The registry has no such record, so the token is a typo or an
                # extraction artifact. Not a deposit, and not a curation gap.
                meta["kind"] = "not-an-accession"
                meta["source_of_kind"] = "registry (no such record)"

        if declared or repos:
            rows.append({
                "id": d["id"],
                "n_availability_sections": len(d.get("availability", [])),
                "accessions": declared,
                "code_repos": repos,
            })

    n_acc = sum(len(r["accessions"]) for r in rows)
    print(f"refs with a declared accession or code repo: {len(rows)}")
    print(f"accessions declared                        : {n_acc}")
    print(f"code repositories declared                 : "
          f"{sum(len(r['code_repos']) for r in rows)}")
    by_reg = Counter(v["registry"] for r in rows for v in r["accessions"].values())
    print("\nby registry:")
    for reg, k in by_reg.most_common():
        print(f"  {k:>4}  {reg}")
    # Where it came from is a fact; what it means is a guess. Print the fact
    # first and give it the emphasis.
    by_src = Counter("table" if v["where"] == "table" else "availability statement"
                     for r in rows for v in r["accessions"].values())
    print("\nby source (factual):")
    for src, k in by_src.most_common():
        print(f"  {k:>4}  {src}")
    print("  A table hit carries no sentence to interpret, and a table of data")
    print("  SOURCES looks exactly like a table of deposits, so these are never")
    print("  called deposits.")

    by_kind = Counter(v["kind"] for r in rows for v in r["accessions"].values())
    by_evi = Counter(v.get("source_of_kind", "sentence")
                     for r in rows for v in r["accessions"].values())
    print("\nby kind:")
    for kind in ("deposit", "reuse", "unclear", "not-an-accession"):
        print(f"  {by_kind.get(kind, 0):>4}  {kind}")
    print("\nwhat decided the kind:")
    for src, k in by_evi.most_common():
        print(f"  {k:>4}  {src}")
    if not cites:
        print("  No registry evidence loaded. Run fetch_accession_citations.py to")
        print("  replace the sentence guess with what the record actually says.")
    else:
        print("  'registry' means the record's own citation settled it. 'sentence'")
        print("  means it did not, and the reading of the surrounding text stands.")
        print("  'registry-silent' means the record links no paper at all, which is")
        print("  common for recent deposits and is not evidence either way.")
        print("  'registry (title join)' matched the record to the paper by title")
        print("  because one side has no PubMed id -- weaker, and worth reading.")
        print("  'registry (no such record)' means the token is not an accession:")
        print("  a typo or an OCR artifact, so neither a deposit nor a gap.")

    if args.orphans:
        print("\n--- DEPOSITS the paper announces that the repo does not mention ---")
        print("    A curation input, not a verdict: CAAIL may hold the parent")
        print("     accession, or may have judged the deposit out of scope.\n")
        n_orphan = n_dep_orphan = n_code_orphan = 0
        code_rows = []
        for r in rows:
            missing = {t: v for t, v in r["accessions"].items()
                       if not repo_mentions(t)}
            if not missing:
                continue
            n_orphan += len(missing)
            deposits = {t: v for t, v in missing.items() if v["kind"] == "deposit"}
            # A deposited GitHub release archive is the paper's own, but it is
            # code: its home is the reference's `> **Code**:` blockquote, not an
            # entry in Datasets/. Merging the two hands a curator a list whose
            # rows need different decisions.
            code = {t: v for t, v in deposits.items()
                    if v.get("content") == "software"}
            data = {t: v for t, v in deposits.items() if t not in code}
            n_dep_orphan += len(data)
            n_code_orphan += len(code)
            if data:
                print(f'  ref {r["id"]}:')
                for tok, v in sorted(data.items()):
                    print(f'    {tok:<26} {v["registry"]:<14} '
                          f'p{v["page"]} {v["where"][:32]}')
            if code:
                code_rows.append((r["id"], sorted(code)))
            r["orphans"] = sorted(missing)
            r["deposit_orphans"] = sorted(data)
            r["code_deposit_orphans"] = sorted(code)
        print(f"\n{n_dep_orphan} DATA accessions classified as deposits are absent from the repo.")
        if code_rows:
            print(f"\n--- and {n_code_orphan} deposited CODE archives (Zenodo software) ---")
            print("    These belong beside the reference as `> **Code**:`, not in")
            print("    Datasets/. Listed separately because the decision differs.\n")
            for rid, toks in code_rows:
                print(f'  ref {rid}: {", ".join(toks)}')
        print(f"\n{n_orphan} of {n_acc} declared accessions are absent overall, but most of")
        print("that number is reused public data the paper cites, which CAAIL has no")
        print("obligation to inventory. Read the deposit figure, not the total.")

    if args.json:
        Path(args.json).write_text(json.dumps(rows, indent=2))
        print(f"\nwrote {args.json}")


if __name__ == "__main__":
    main()
